export const LOAD_MOVIE_LIST = 'LOAD_MOVIE_LIST';

export const OPEN_MOVIE_RATER = 'OPEN_MOVIE_RATER';
export const CLOSE_MOVIE_RATER = 'CLOSE_MOVIE_RATER';

export const UPDATE_MOVIE_RANK = 'UPDATE_MOVIE_RANK';